// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Twind from "twind";
import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as Css from "twind/css";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MxLibs__BreakpointSub from "@mxcins/webapi/src/breakpoint-sub/MxLibs__BreakpointSub.bs.js";

var init = "flex";

function make(className, wrap, justify, align, space) {
  var classes = [init];
  classes.push(wrap ? "flex-wrap" : "flex-nowrap");
  classes.push(justify === "space-between" ? "justify-space-between" : (
          justify === "end" ? "justify-end" : (
              justify === "start" ? "justify-start" : (
                  justify === "center" ? "justify-center" : "justify-space-around"
                )
            )
        ));
  classes.push(align === "start" ? "items-start" : (
          align === "center" ? "items-center" : "items-end"
        ));
  var y = space[1];
  var x = space[0];
  if (x !== 0) {
    var str = Css.css({
          "column-gap": x.toString() + "px;"
        });
    classes.push(str);
  }
  if (y !== 0) {
    var str$1 = Css.css({
          "row-gap": y.toString() + "px;"
        });
    classes.push(str$1);
  }
  var match = Twind.tw(Twind.apply(classes));
  if (className !== undefined) {
    return [
              match,
              className
            ].join(" ");
  } else {
    return match;
  }
}

var GridRowTwind = {
  init: init,
  make: make
};

function MxRC__Grid__Row(Props) {
  var className = Props.className;
  var style = Props.style;
  var wrapOpt = Props.wrap;
  var justifyOpt = Props.justify;
  var alignOpt = Props.align;
  var space = Props.space;
  var mspace = Props.mspace;
  var children = Props.children;
  var wrap = wrapOpt !== undefined ? wrapOpt : true;
  var justify = justifyOpt !== undefined ? justifyOpt : "start";
  var align = alignOpt !== undefined ? alignOpt : "start";
  var spaceRef = React.useRef(space);
  var mspaceRef = React.useRef(mspace);
  var match = React.useState(function () {
        return MxLibs__BreakpointSub.breakpoints;
      });
  var setScreens = match[1];
  var screens = match[0];
  React.useLayoutEffect((function () {
          var token = MxLibs__BreakpointSub.subscribe(function (screens) {
                return Belt_Option.forEach(mspaceRef.current, (function (param) {
                              return Curry._1(setScreens, (function (param) {
                                            return screens;
                                          }));
                            }));
              });
          return (function (param) {
                    return MxLibs__BreakpointSub.unsubscribe(token);
                  });
        }), []);
  var match$1 = spaceRef.current;
  var match$2 = mspaceRef.current;
  var space$1;
  if (match$1 !== undefined) {
    if (match$2 !== undefined) {
      console.warn("`space` or `mspace` only can be set one");
      space$1 = match$1;
    } else {
      space$1 = match$1;
    }
  } else if (match$2 !== undefined) {
    var mx = Belt_Map.fromArray(match$2[0], MxLibs__BreakpointSub.BreakpointPubSub.BreakpointCmp);
    var my = Belt_Map.fromArray(match$2[1], MxLibs__BreakpointSub.BreakpointPubSub.BreakpointCmp);
    var mx$1 = Belt_Map.findFirstBy(mx, (function (k, param) {
            return screens.includes(k);
          }));
    var my$1 = Belt_Map.findFirstBy(my, (function (k, param) {
            return screens.includes(k);
          }));
    var mx$2 = Belt_Option.map(mx$1, (function (param) {
            return param[1];
          }));
    var my$2 = Belt_Option.map(my$1, (function (param) {
            return param[1];
          }));
    space$1 = [
      Belt_Option.getWithDefault(mx$2, 0),
      Belt_Option.getWithDefault(my$2, 0)
    ];
  } else {
    space$1 = [
      0,
      0
    ];
  }
  var className$1 = make(className, wrap, justify, align, space$1);
  var children$1 = Belt_Option.getWithDefault(children, null);
  var tmp = {
    className: className$1
  };
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  return React.createElement("div", tmp, children$1);
}

var make$1 = MxRC__Grid__Row;

export {
  GridRowTwind ,
  make$1 as make,
  
}
/* react Not a pure module */
