// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as MxWebapi__BreakpointSub from "@mxcins/webapi/src/breakpoint-sub/MxWebapi__BreakpointSub.bs.js";

function useBreakpoint(param) {
  var match = React.useState(function () {
        return [];
      });
  var set = match[1];
  React.useEffect((function () {
          var id = MxWebapi__BreakpointSub.subscribe(function (screens) {
                return Curry._1(set, (function (param) {
                              return screens;
                            }));
              });
          return (function (param) {
                    return MxWebapi__BreakpointSub.unsubscribe(id);
                  });
        }), []);
  return match[0];
}

export {
  useBreakpoint ,
  
}
/* react Not a pure module */
