// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as MxHooks_useObserveResize from "./MxHooks_useObserveResize.js";

function useGetState(init) {
  var match = React.useState(function () {
        return Curry._1(init, undefined);
      });
  var state = match[0];
  var ref = React.useRef(state);
  ref.current = state;
  var get = React.useCallback(function (param) {
        return ref.current;
      });
  return [
          state,
          match[1],
          get
        ];
}

var useObserveResize = MxHooks_useObserveResize.useObserveResize;

export {
  useGetState ,
  useObserveResize ,
  
}
/* react Not a pure module */
