// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Twind from "twind";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var init = "flex-auto min-h-0";

function make(className) {
  var classes = [init];
  var match = Twind.tw(Twind.apply(classes));
  if (className !== undefined) {
    return [
              match,
              className
            ].join(" ");
  } else {
    return match;
  }
}

var LayoutContentTwind = {
  init: init,
  make: make
};

function MxRC__Layout__Content(Props) {
  var className = Props.className;
  var style = Props.style;
  var children = Props.children;
  var className$1 = make(className);
  var children$1 = Belt_Option.getWithDefault(children, null);
  var tmp = {
    className: className$1
  };
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  return React.createElement("main", tmp, children$1);
}

var make$1 = MxRC__Layout__Content;

export {
  LayoutContentTwind ,
  make$1 as make,
  
}
/* react Not a pure module */
