// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MxRC__Colord from "./MxRC__Colord.bs.js";
import * as Content from "@twind/content";
import * as Colors from "@ant-design/colors";

var background = MxRC__Colord.RGB.toS(MxRC__Colord.hsv2rgb(MxRC__Colord.HSV.make(0, 0.0, 0.96, undefined, undefined)));

console.log("colors", Colors.presetPalettes);

var conf = {
  darkMode: "class",
  plugins: {
    content: Content.content
  },
  preflight: {
    ":root": {
      "--color-primary": Colors.presetPalettes.blue.primary,
      "--color-primary-hover": Colors.presetPalettes.blue[4],
      "--color-primary-active": Colors.presetPalettes.blue[6],
      "--color-danger": Colors.presetPalettes.red.primary,
      "--color-danger-hover": Colors.presetPalettes.red[4],
      "--color-danger-active": Colors.presetPalettes.red[6],
      "--color-link": Colors.presetPalettes.blue.primary,
      "--color-link-hover": Colors.presetPalettes.blue[4],
      "--color-link-active": Colors.presetPalettes.blue[6]
    },
    "button:focus": {
      outline: "0"
    },
    svg: {
      "vertical-align": "initial"
    }
  },
  theme: {
    content: {
      empty: "\"\""
    },
    colors: {
      initial: "initial",
      transparent: "transparent",
      white: "#fff",
      black: "#000",
      primary: {
        DEFAULT: "var(--color-primary)",
        hover: "var(--color-primary-hover)",
        active: "var(--color-primary-active)"
      },
      danger: {
        DEFAULT: "var(--color-danger)",
        hover: "var(--color-danger-hover)",
        active: "var(--color-danger-active)"
      },
      link: {
        DEFAULT: "var(--color-link)",
        hover: "var(--color-link-hover)",
        active: "var(--color-link-active)"
      },
      text: {
        DEFAULT: "rgba(0, 0, 0, .85)",
        disabled: "rgba(0, 0, 0, 0.25)"
      },
      background: {
        disabled: background
      },
      border: {
        DEFAULT: MxRC__Colord.RGB.toS(MxRC__Colord.hsv2rgb(MxRC__Colord.HSV.make(0, 0.0, 0.85, 0.5, undefined)))
      }
    },
    fontSize: {
      xs: [
        "0.75rem",
        {
          lineHeight: "1rem"
        }
      ],
      sm: [
        "0.875rem",
        {
          lineHeight: "1.375rem"
        }
      ],
      base: [
        "1rem",
        {
          lineHeight: "1.5rem"
        }
      ],
      lg: [
        "1.125rem",
        {
          lineHeight: "1.75rem"
        }
      ],
      xl: [
        "1.25rem",
        {
          lineHeight: "1.75rem"
        }
      ]
    },
    padding: (theme => {
        const spacing = theme('spacing');
        console.log('spacing', spacing);
        return {
          ...spacing,
          '4-bordered': `calc(${spacing[4]} - 1px)`,
        };
      }),
    minWidth: (theme => theme('width'))
  }
};

export {
  background ,
  conf ,
  
}
/* background Not a pure module */
