// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ExternalsJs from "./_externals.js";

function anyToBreakpointRecord(prim) {
  return ExternalsJs.anyToBreakpointRecord(prim);
}

function anyToTwoBreakpointRecord(prim) {
  return ExternalsJs.anyToTwoBreakpointRecord(prim);
}

function isBreakpointRecord(prim) {
  return ExternalsJs.isBreakpointRecord(prim);
}

function makeSpacingByBreakpoints(prim0, prim1) {
  return ExternalsJs.makeSpacingByBreakpoints(prim0, prim1);
}

var BreakpointUtils = {
  anyToBreakpointRecord: anyToBreakpointRecord,
  anyToTwoBreakpointRecord: anyToTwoBreakpointRecord,
  isBreakpointRecord: isBreakpointRecord,
  makeSpacingByBreakpoints: makeSpacingByBreakpoints
};

export {
  BreakpointUtils ,
  
}
/* ./_externals.js Not a pure module */
