// Generated by ReScript, PLEASE EDIT WITH CARE


var AccountBookFilled = {};

var AccountBookOutlined = {};

var AccountBookTwoTone = {};

var AimOutlined = {};

var AlertFilled = {};

var AlertOutlined = {};

var AlertTwoTone = {};

var AlibabaOutlined = {};

var AlignCenterOutlined = {};

var AlignLeftOutlined = {};

var AlignRightOutlined = {};

var AlipayCircleFilled = {};

var AlipayCircleOutlined = {};

var AlipayOutlined = {};

var AlipaySquareFilled = {};

var AliwangwangFilled = {};

var AliwangwangOutlined = {};

var AliyunOutlined = {};

var AmazonCircleFilled = {};

var AmazonOutlined = {};

var AmazonSquareFilled = {};

var AndroidFilled = {};

var AndroidOutlined = {};

var AntCloudOutlined = {};

var AntDesignOutlined = {};

var ApartmentOutlined = {};

var ApiFilled = {};

var ApiOutlined = {};

var ApiTwoTone = {};

var AppleFilled = {};

var AppleOutlined = {};

var AppstoreAddOutlined = {};

var AppstoreFilled = {};

var AppstoreOutlined = {};

var AppstoreTwoTone = {};

var AreaChartOutlined = {};

var ArrowDownOutlined = {};

var ArrowLeftOutlined = {};

var ArrowRightOutlined = {};

var ArrowUpOutlined = {};

var ArrowsAltOutlined = {};

var AudioFilled = {};

var AudioMutedOutlined = {};

var AudioOutlined = {};

var AudioTwoTone = {};

var AuditOutlined = {};

var BackwardFilled = {};

var BackwardOutlined = {};

var BankFilled = {};

var BankOutlined = {};

var BankTwoTone = {};

var BarChartOutlined = {};

var BarcodeOutlined = {};

var BarsOutlined = {};

var BehanceCircleFilled = {};

var BehanceOutlined = {};

var BehanceSquareFilled = {};

var BehanceSquareOutlined = {};

var BellFilled = {};

var BellOutlined = {};

var BellTwoTone = {};

var BgColorsOutlined = {};

var BlockOutlined = {};

var BoldOutlined = {};

var BookFilled = {};

var BookOutlined = {};

var BookTwoTone = {};

var BorderBottomOutlined = {};

var BorderHorizontalOutlined = {};

var BorderInnerOutlined = {};

var BorderLeftOutlined = {};

var BorderOuterOutlined = {};

var BorderOutlined = {};

var BorderRightOutlined = {};

var BorderTopOutlined = {};

var BorderVerticleOutlined = {};

var BorderlessTableOutlined = {};

var BoxPlotFilled = {};

var BoxPlotOutlined = {};

var BoxPlotTwoTone = {};

var BranchesOutlined = {};

var BugFilled = {};

var BugOutlined = {};

var BugTwoTone = {};

var BuildFilled = {};

var BuildOutlined = {};

var BuildTwoTone = {};

var BulbFilled = {};

var BulbOutlined = {};

var BulbTwoTone = {};

var CalculatorFilled = {};

var CalculatorOutlined = {};

var CalculatorTwoTone = {};

var CalendarFilled = {};

var CalendarOutlined = {};

var CalendarTwoTone = {};

var CameraFilled = {};

var CameraOutlined = {};

var CameraTwoTone = {};

var CarFilled = {};

var CarOutlined = {};

var CarTwoTone = {};

var CaretDownFilled = {};

var CaretDownOutlined = {};

var CaretLeftFilled = {};

var CaretLeftOutlined = {};

var CaretRightFilled = {};

var CaretRightOutlined = {};

var CaretUpFilled = {};

var CaretUpOutlined = {};

var CarryOutFilled = {};

var CarryOutOutlined = {};

var CarryOutTwoTone = {};

var CheckCircleFilled = {};

var CheckCircleOutlined = {};

var CheckCircleTwoTone = {};

var CheckOutlined = {};

var CheckSquareFilled = {};

var CheckSquareOutlined = {};

var CheckSquareTwoTone = {};

var ChromeFilled = {};

var ChromeOutlined = {};

var CiCircleFilled = {};

var CiCircleOutlined = {};

var CiCircleTwoTone = {};

var CiOutlined = {};

var CiTwoTone = {};

var ClearOutlined = {};

var ClockCircleFilled = {};

var ClockCircleOutlined = {};

var ClockCircleTwoTone = {};

var CloseCircleFilled = {};

var CloseCircleOutlined = {};

var CloseCircleTwoTone = {};

var CloseOutlined = {};

var CloseSquareFilled = {};

var CloseSquareOutlined = {};

var CloseSquareTwoTone = {};

var CloudDownloadOutlined = {};

var CloudFilled = {};

var CloudOutlined = {};

var CloudServerOutlined = {};

var CloudSyncOutlined = {};

var CloudTwoTone = {};

var CloudUploadOutlined = {};

var ClusterOutlined = {};

var CodeFilled = {};

var CodeOutlined = {};

var CodeSandboxCircleFilled = {};

var CodeSandboxOutlined = {};

var CodeSandboxSquareFilled = {};

var CodeTwoTone = {};

var CodepenCircleFilled = {};

var CodepenCircleOutlined = {};

var CodepenOutlined = {};

var CodepenSquareFilled = {};

var CoffeeOutlined = {};

var ColumnHeightOutlined = {};

var ColumnWidthOutlined = {};

var CommentOutlined = {};

var CompassFilled = {};

var CompassOutlined = {};

var CompassTwoTone = {};

var CompressOutlined = {};

var ConsoleSqlOutlined = {};

var ContactsFilled = {};

var ContactsOutlined = {};

var ContactsTwoTone = {};

var ContainerFilled = {};

var ContainerOutlined = {};

var ContainerTwoTone = {};

var ControlFilled = {};

var ControlOutlined = {};

var ControlTwoTone = {};

var CopyFilled = {};

var CopyOutlined = {};

var CopyTwoTone = {};

var CopyrightCircleFilled = {};

var CopyrightCircleOutlined = {};

var CopyrightCircleTwoTone = {};

var CopyrightOutlined = {};

var CopyrightTwoTone = {};

var CreditCardFilled = {};

var CreditCardOutlined = {};

var CreditCardTwoTone = {};

var CrownFilled = {};

var CrownOutlined = {};

var CrownTwoTone = {};

var CustomerServiceFilled = {};

var CustomerServiceOutlined = {};

var CustomerServiceTwoTone = {};

var DashOutlined = {};

var DashboardFilled = {};

var DashboardOutlined = {};

var DashboardTwoTone = {};

var DatabaseFilled = {};

var DatabaseOutlined = {};

var DatabaseTwoTone = {};

var DeleteColumnOutlined = {};

var DeleteFilled = {};

var DeleteOutlined = {};

var DeleteRowOutlined = {};

var DeleteTwoTone = {};

var DeliveredProcedureOutlined = {};

var DeploymentUnitOutlined = {};

var DesktopOutlined = {};

var DiffFilled = {};

var DiffOutlined = {};

var DiffTwoTone = {};

var DingdingOutlined = {};

var DingtalkCircleFilled = {};

var DingtalkOutlined = {};

var DingtalkSquareFilled = {};

var DisconnectOutlined = {};

var DislikeFilled = {};

var DislikeOutlined = {};

var DislikeTwoTone = {};

var DollarCircleFilled = {};

var DollarCircleOutlined = {};

var DollarCircleTwoTone = {};

var DollarOutlined = {};

var DollarTwoTone = {};

var DotChartOutlined = {};

var DoubleLeftOutlined = {};

var DoubleRightOutlined = {};

var DownCircleFilled = {};

var DownCircleOutlined = {};

var DownCircleTwoTone = {};

var DownOutlined = {};

var DownSquareFilled = {};

var DownSquareOutlined = {};

var DownSquareTwoTone = {};

var DownloadOutlined = {};

var DragOutlined = {};

var DribbbleCircleFilled = {};

var DribbbleOutlined = {};

var DribbbleSquareFilled = {};

var DribbbleSquareOutlined = {};

var DropboxCircleFilled = {};

var DropboxOutlined = {};

var DropboxSquareFilled = {};

var EditFilled = {};

var EditOutlined = {};

var EditTwoTone = {};

var EllipsisOutlined = {};

var EnterOutlined = {};

var EnvironmentFilled = {};

var EnvironmentOutlined = {};

var EnvironmentTwoTone = {};

var EuroCircleFilled = {};

var EuroCircleOutlined = {};

var EuroCircleTwoTone = {};

var EuroOutlined = {};

var EuroTwoTone = {};

var ExceptionOutlined = {};

var ExclamationCircleFilled = {};

var ExclamationCircleOutlined = {};

var ExclamationCircleTwoTone = {};

var ExclamationOutlined = {};

var ExpandAltOutlined = {};

var ExpandOutlined = {};

var ExperimentFilled = {};

var ExperimentOutlined = {};

var ExperimentTwoTone = {};

var ExportOutlined = {};

var EyeFilled = {};

var EyeInvisibleFilled = {};

var EyeInvisibleOutlined = {};

var EyeInvisibleTwoTone = {};

var EyeOutlined = {};

var EyeTwoTone = {};

var FacebookFilled = {};

var FacebookOutlined = {};

var FallOutlined = {};

var FastBackwardFilled = {};

var FastBackwardOutlined = {};

var FastForwardFilled = {};

var FastForwardOutlined = {};

var FieldBinaryOutlined = {};

var FieldNumberOutlined = {};

var FieldStringOutlined = {};

var FieldTimeOutlined = {};

var FileAddFilled = {};

var FileAddOutlined = {};

var FileAddTwoTone = {};

var FileDoneOutlined = {};

var FileExcelFilled = {};

var FileExcelOutlined = {};

var FileExcelTwoTone = {};

var FileExclamationFilled = {};

var FileExclamationOutlined = {};

var FileExclamationTwoTone = {};

var FileFilled = {};

var FileGifOutlined = {};

var FileImageFilled = {};

var FileImageOutlined = {};

var FileImageTwoTone = {};

var FileJpgOutlined = {};

var FileMarkdownFilled = {};

var FileMarkdownOutlined = {};

var FileMarkdownTwoTone = {};

var FileOutlined = {};

var FilePdfFilled = {};

var FilePdfOutlined = {};

var FilePdfTwoTone = {};

var FilePptFilled = {};

var FilePptOutlined = {};

var FilePptTwoTone = {};

var FileProtectOutlined = {};

var FileSearchOutlined = {};

var FileSyncOutlined = {};

var FileTextFilled = {};

var FileTextOutlined = {};

var FileTextTwoTone = {};

var FileTwoTone = {};

var FileUnknownFilled = {};

var FileUnknownOutlined = {};

var FileUnknownTwoTone = {};

var FileWordFilled = {};

var FileWordOutlined = {};

var FileWordTwoTone = {};

var FileZipFilled = {};

var FileZipOutlined = {};

var FileZipTwoTone = {};

var FilterFilled = {};

var FilterOutlined = {};

var FilterTwoTone = {};

var FireFilled = {};

var FireOutlined = {};

var FireTwoTone = {};

var FlagFilled = {};

var FlagOutlined = {};

var FlagTwoTone = {};

var FolderAddFilled = {};

var FolderAddOutlined = {};

var FolderAddTwoTone = {};

var FolderFilled = {};

var FolderOpenFilled = {};

var FolderOpenOutlined = {};

var FolderOpenTwoTone = {};

var FolderOutlined = {};

var FolderTwoTone = {};

var FolderViewOutlined = {};

var FontColorsOutlined = {};

var FontSizeOutlined = {};

var ForkOutlined = {};

var FormOutlined = {};

var FormatPainterFilled = {};

var FormatPainterOutlined = {};

var ForwardFilled = {};

var ForwardOutlined = {};

var FrownFilled = {};

var FrownOutlined = {};

var FrownTwoTone = {};

var FullscreenExitOutlined = {};

var FullscreenOutlined = {};

var FunctionOutlined = {};

var FundFilled = {};

var FundOutlined = {};

var FundProjectionScreenOutlined = {};

var FundTwoTone = {};

var FundViewOutlined = {};

var FunnelPlotFilled = {};

var FunnelPlotOutlined = {};

var FunnelPlotTwoTone = {};

var GatewayOutlined = {};

var GifOutlined = {};

var GiftFilled = {};

var GiftOutlined = {};

var GiftTwoTone = {};

var GithubFilled = {};

var GithubOutlined = {};

var GitlabFilled = {};

var GitlabOutlined = {};

var GlobalOutlined = {};

var GoldFilled = {};

var GoldOutlined = {};

var GoldTwoTone = {};

var GoldenFilled = {};

var GoogleCircleFilled = {};

var GoogleOutlined = {};

var GooglePlusCircleFilled = {};

var GooglePlusOutlined = {};

var GooglePlusSquareFilled = {};

var GoogleSquareFilled = {};

var GroupOutlined = {};

var HddFilled = {};

var HddOutlined = {};

var HddTwoTone = {};

var HeartFilled = {};

var HeartOutlined = {};

var HeartTwoTone = {};

var HeatMapOutlined = {};

var HighlightFilled = {};

var HighlightOutlined = {};

var HighlightTwoTone = {};

var HistoryOutlined = {};

var HolderOutlined = {};

var HomeFilled = {};

var HomeOutlined = {};

var HomeTwoTone = {};

var HourglassFilled = {};

var HourglassOutlined = {};

var HourglassTwoTone = {};

var Html5Filled = {};

var Html5Outlined = {};

var Html5TwoTone = {};

var IdcardFilled = {};

var IdcardOutlined = {};

var IdcardTwoTone = {};

var IeCircleFilled = {};

var IeOutlined = {};

var IeSquareFilled = {};

var ImportOutlined = {};

var InboxOutlined = {};

var InfoCircleFilled = {};

var InfoCircleOutlined = {};

var InfoCircleTwoTone = {};

var InfoOutlined = {};

var InsertRowAboveOutlined = {};

var InsertRowBelowOutlined = {};

var InsertRowLeftOutlined = {};

var InsertRowRightOutlined = {};

var InstagramFilled = {};

var InstagramOutlined = {};

var InsuranceFilled = {};

var InsuranceOutlined = {};

var InsuranceTwoTone = {};

var InteractionFilled = {};

var InteractionOutlined = {};

var InteractionTwoTone = {};

var IssuesCloseOutlined = {};

var ItalicOutlined = {};

var KeyOutlined = {};

var LaptopOutlined = {};

var LayoutFilled = {};

var LayoutOutlined = {};

var LayoutTwoTone = {};

var LeftCircleFilled = {};

var LeftCircleOutlined = {};

var LeftCircleTwoTone = {};

var LeftOutlined = {};

var LeftSquareFilled = {};

var LeftSquareOutlined = {};

var LeftSquareTwoTone = {};

var LikeFilled = {};

var LikeOutlined = {};

var LikeTwoTone = {};

var LineChartOutlined = {};

var LineHeightOutlined = {};

var LineOutlined = {};

var LinkOutlined = {};

var LinkedinFilled = {};

var LinkedinOutlined = {};

var Loading3QuartersOutlined = {};

var LoadingOutlined = {};

var LockFilled = {};

var LockOutlined = {};

var LockTwoTone = {};

var LoginOutlined = {};

var LogoutOutlined = {};

var MacCommandFilled = {};

var MacCommandOutlined = {};

var MailFilled = {};

var MailOutlined = {};

var MailTwoTone = {};

var ManOutlined = {};

var MedicineBoxFilled = {};

var MedicineBoxOutlined = {};

var MedicineBoxTwoTone = {};

var MediumCircleFilled = {};

var MediumOutlined = {};

var MediumSquareFilled = {};

var MediumWorkmarkOutlined = {};

var MehFilled = {};

var MehOutlined = {};

var MehTwoTone = {};

var MenuFoldOutlined = {};

var MenuOutlined = {};

var MenuUnfoldOutlined = {};

var MergeCellsOutlined = {};

var MessageFilled = {};

var MessageOutlined = {};

var MessageTwoTone = {};

var MinusCircleFilled = {};

var MinusCircleOutlined = {};

var MinusCircleTwoTone = {};

var MinusOutlined = {};

var MinusSquareFilled = {};

var MinusSquareOutlined = {};

var MinusSquareTwoTone = {};

var MobileFilled = {};

var MobileOutlined = {};

var MobileTwoTone = {};

var MoneyCollectFilled = {};

var MoneyCollectOutlined = {};

var MoneyCollectTwoTone = {};

var MonitorOutlined = {};

var MoreOutlined = {};

var NodeCollapseOutlined = {};

var NodeExpandOutlined = {};

var NodeIndexOutlined = {};

var NotificationFilled = {};

var NotificationOutlined = {};

var NotificationTwoTone = {};

var NumberOutlined = {};

var OneToOneOutlined = {};

var OrderedListOutlined = {};

var PaperClipOutlined = {};

var PartitionOutlined = {};

var PauseCircleFilled = {};

var PauseCircleOutlined = {};

var PauseCircleTwoTone = {};

var PauseOutlined = {};

var PayCircleFilled = {};

var PayCircleOutlined = {};

var PercentageOutlined = {};

var PhoneFilled = {};

var PhoneOutlined = {};

var PhoneTwoTone = {};

var PicCenterOutlined = {};

var PicLeftOutlined = {};

var PicRightOutlined = {};

var PictureFilled = {};

var PictureOutlined = {};

var PictureTwoTone = {};

var PieChartFilled = {};

var PieChartOutlined = {};

var PieChartTwoTone = {};

var PlayCircleFilled = {};

var PlayCircleOutlined = {};

var PlayCircleTwoTone = {};

var PlaySquareFilled = {};

var PlaySquareOutlined = {};

var PlaySquareTwoTone = {};

var PlusCircleFilled = {};

var PlusCircleOutlined = {};

var PlusCircleTwoTone = {};

var PlusOutlined = {};

var PlusSquareFilled = {};

var PlusSquareOutlined = {};

var PlusSquareTwoTone = {};

var PoundCircleFilled = {};

var PoundCircleOutlined = {};

var PoundCircleTwoTone = {};

var PoundOutlined = {};

var PoweroffOutlined = {};

var PrinterFilled = {};

var PrinterOutlined = {};

var PrinterTwoTone = {};

var ProfileFilled = {};

var ProfileOutlined = {};

var ProfileTwoTone = {};

var ProjectFilled = {};

var ProjectOutlined = {};

var ProjectTwoTone = {};

var PropertySafetyFilled = {};

var PropertySafetyOutlined = {};

var PropertySafetyTwoTone = {};

var PullRequestOutlined = {};

var PushpinFilled = {};

var PushpinOutlined = {};

var PushpinTwoTone = {};

var QqCircleFilled = {};

var QqOutlined = {};

var QqSquareFilled = {};

var QrcodeOutlined = {};

var QuestionCircleFilled = {};

var QuestionCircleOutlined = {};

var QuestionCircleTwoTone = {};

var QuestionOutlined = {};

var RadarChartOutlined = {};

var RadiusBottomleftOutlined = {};

var RadiusBottomrightOutlined = {};

var RadiusSettingOutlined = {};

var RadiusUpleftOutlined = {};

var RadiusUprightOutlined = {};

var ReadFilled = {};

var ReadOutlined = {};

var ReconciliationFilled = {};

var ReconciliationOutlined = {};

var ReconciliationTwoTone = {};

var RedEnvelopeFilled = {};

var RedEnvelopeOutlined = {};

var RedEnvelopeTwoTone = {};

var RedditCircleFilled = {};

var RedditOutlined = {};

var RedditSquareFilled = {};

var RedoOutlined = {};

var ReloadOutlined = {};

var RestFilled = {};

var RestOutlined = {};

var RestTwoTone = {};

var RetweetOutlined = {};

var RightCircleFilled = {};

var RightCircleOutlined = {};

var RightCircleTwoTone = {};

var RightOutlined = {};

var RightSquareFilled = {};

var RightSquareOutlined = {};

var RightSquareTwoTone = {};

var RiseOutlined = {};

var RobotFilled = {};

var RobotOutlined = {};

var RocketFilled = {};

var RocketOutlined = {};

var RocketTwoTone = {};

var RollbackOutlined = {};

var RotateLeftOutlined = {};

var RotateRightOutlined = {};

var SafetyCertificateFilled = {};

var SafetyCertificateOutlined = {};

var SafetyCertificateTwoTone = {};

var SafetyOutlined = {};

var SaveFilled = {};

var SaveOutlined = {};

var SaveTwoTone = {};

var ScanOutlined = {};

var ScheduleFilled = {};

var ScheduleOutlined = {};

var ScheduleTwoTone = {};

var ScissorOutlined = {};

var SearchOutlined = {};

var SecurityScanFilled = {};

var SecurityScanOutlined = {};

var SecurityScanTwoTone = {};

var SelectOutlined = {};

var SendOutlined = {};

var SettingFilled = {};

var SettingOutlined = {};

var SettingTwoTone = {};

var ShakeOutlined = {};

var ShareAltOutlined = {};

var ShopFilled = {};

var ShopOutlined = {};

var ShopTwoTone = {};

var ShoppingCartOutlined = {};

var ShoppingFilled = {};

var ShoppingOutlined = {};

var ShoppingTwoTone = {};

var ShrinkOutlined = {};

var SignalFilled = {};

var SisternodeOutlined = {};

var SketchCircleFilled = {};

var SketchOutlined = {};

var SketchSquareFilled = {};

var SkinFilled = {};

var SkinOutlined = {};

var SkinTwoTone = {};

var SkypeFilled = {};

var SkypeOutlined = {};

var SlackCircleFilled = {};

var SlackOutlined = {};

var SlackSquareFilled = {};

var SlackSquareOutlined = {};

var SlidersFilled = {};

var SlidersOutlined = {};

var SlidersTwoTone = {};

var SmallDashOutlined = {};

var SmileFilled = {};

var SmileOutlined = {};

var SmileTwoTone = {};

var SnippetsFilled = {};

var SnippetsOutlined = {};

var SnippetsTwoTone = {};

var SolutionOutlined = {};

var SortAscendingOutlined = {};

var SortDescendingOutlined = {};

var SoundFilled = {};

var SoundOutlined = {};

var SoundTwoTone = {};

var SplitCellsOutlined = {};

var StarFilled = {};

var StarOutlined = {};

var StarTwoTone = {};

var StepBackwardFilled = {};

var StepBackwardOutlined = {};

var StepForwardFilled = {};

var StepForwardOutlined = {};

var StockOutlined = {};

var StopFilled = {};

var StopOutlined = {};

var StopTwoTone = {};

var StrikethroughOutlined = {};

var SubnodeOutlined = {};

var SwapLeftOutlined = {};

var SwapOutlined = {};

var SwapRightOutlined = {};

var SwitcherFilled = {};

var SwitcherOutlined = {};

var SwitcherTwoTone = {};

var SyncOutlined = {};

var TableOutlined = {};

var TabletFilled = {};

var TabletOutlined = {};

var TabletTwoTone = {};

var TagFilled = {};

var TagOutlined = {};

var TagTwoTone = {};

var TagsFilled = {};

var TagsOutlined = {};

var TagsTwoTone = {};

var TaobaoCircleFilled = {};

var TaobaoCircleOutlined = {};

var TaobaoOutlined = {};

var TaobaoSquareFilled = {};

var TeamOutlined = {};

var ThunderboltFilled = {};

var ThunderboltOutlined = {};

var ThunderboltTwoTone = {};

var ToTopOutlined = {};

var ToolFilled = {};

var ToolOutlined = {};

var ToolTwoTone = {};

var TrademarkCircleFilled = {};

var TrademarkCircleOutlined = {};

var TrademarkCircleTwoTone = {};

var TrademarkOutlined = {};

var TransactionOutlined = {};

var TranslationOutlined = {};

var TrophyFilled = {};

var TrophyOutlined = {};

var TrophyTwoTone = {};

var TwitterCircleFilled = {};

var TwitterOutlined = {};

var TwitterSquareFilled = {};

var UnderlineOutlined = {};

var UndoOutlined = {};

var UngroupOutlined = {};

var UnlockFilled = {};

var UnlockOutlined = {};

var UnlockTwoTone = {};

var UnorderedListOutlined = {};

var UpCircleFilled = {};

var UpCircleOutlined = {};

var UpCircleTwoTone = {};

var UpOutlined = {};

var UpSquareFilled = {};

var UpSquareOutlined = {};

var UpSquareTwoTone = {};

var UploadOutlined = {};

var UsbFilled = {};

var UsbOutlined = {};

var UsbTwoTone = {};

var UserAddOutlined = {};

var UserDeleteOutlined = {};

var UserOutlined = {};

var UserSwitchOutlined = {};

var UsergroupAddOutlined = {};

var UsergroupDeleteOutlined = {};

var VerifiedOutlined = {};

var VerticalAlignBottomOutlined = {};

var VerticalAlignMiddleOutlined = {};

var VerticalAlignTopOutlined = {};

var VerticalLeftOutlined = {};

var VerticalRightOutlined = {};

var VideoCameraAddOutlined = {};

var VideoCameraFilled = {};

var VideoCameraOutlined = {};

var VideoCameraTwoTone = {};

var WalletFilled = {};

var WalletOutlined = {};

var WalletTwoTone = {};

var WarningFilled = {};

var WarningOutlined = {};

var WarningTwoTone = {};

var WechatFilled = {};

var WechatOutlined = {};

var WeiboCircleFilled = {};

var WeiboCircleOutlined = {};

var WeiboOutlined = {};

var WeiboSquareFilled = {};

var WeiboSquareOutlined = {};

var WhatsAppOutlined = {};

var WifiOutlined = {};

var WindowsFilled = {};

var WindowsOutlined = {};

var WomanOutlined = {};

var YahooFilled = {};

var YahooOutlined = {};

var YoutubeFilled = {};

var YoutubeOutlined = {};

var YuqueFilled = {};

var YuqueOutlined = {};

var ZhihuCircleFilled = {};

var ZhihuOutlined = {};

var ZhihuSquareFilled = {};

var ZoomInOutlined = {};

var ZoomOutOutlined = {};

export {
  AccountBookFilled ,
  AccountBookOutlined ,
  AccountBookTwoTone ,
  AimOutlined ,
  AlertFilled ,
  AlertOutlined ,
  AlertTwoTone ,
  AlibabaOutlined ,
  AlignCenterOutlined ,
  AlignLeftOutlined ,
  AlignRightOutlined ,
  AlipayCircleFilled ,
  AlipayCircleOutlined ,
  AlipayOutlined ,
  AlipaySquareFilled ,
  AliwangwangFilled ,
  AliwangwangOutlined ,
  AliyunOutlined ,
  AmazonCircleFilled ,
  AmazonOutlined ,
  AmazonSquareFilled ,
  AndroidFilled ,
  AndroidOutlined ,
  AntCloudOutlined ,
  AntDesignOutlined ,
  ApartmentOutlined ,
  ApiFilled ,
  ApiOutlined ,
  ApiTwoTone ,
  AppleFilled ,
  AppleOutlined ,
  AppstoreAddOutlined ,
  AppstoreFilled ,
  AppstoreOutlined ,
  AppstoreTwoTone ,
  AreaChartOutlined ,
  ArrowDownOutlined ,
  ArrowLeftOutlined ,
  ArrowRightOutlined ,
  ArrowUpOutlined ,
  ArrowsAltOutlined ,
  AudioFilled ,
  AudioMutedOutlined ,
  AudioOutlined ,
  AudioTwoTone ,
  AuditOutlined ,
  BackwardFilled ,
  BackwardOutlined ,
  BankFilled ,
  BankOutlined ,
  BankTwoTone ,
  BarChartOutlined ,
  BarcodeOutlined ,
  BarsOutlined ,
  BehanceCircleFilled ,
  BehanceOutlined ,
  BehanceSquareFilled ,
  BehanceSquareOutlined ,
  BellFilled ,
  BellOutlined ,
  BellTwoTone ,
  BgColorsOutlined ,
  BlockOutlined ,
  BoldOutlined ,
  BookFilled ,
  BookOutlined ,
  BookTwoTone ,
  BorderBottomOutlined ,
  BorderHorizontalOutlined ,
  BorderInnerOutlined ,
  BorderLeftOutlined ,
  BorderOuterOutlined ,
  BorderOutlined ,
  BorderRightOutlined ,
  BorderTopOutlined ,
  BorderVerticleOutlined ,
  BorderlessTableOutlined ,
  BoxPlotFilled ,
  BoxPlotOutlined ,
  BoxPlotTwoTone ,
  BranchesOutlined ,
  BugFilled ,
  BugOutlined ,
  BugTwoTone ,
  BuildFilled ,
  BuildOutlined ,
  BuildTwoTone ,
  BulbFilled ,
  BulbOutlined ,
  BulbTwoTone ,
  CalculatorFilled ,
  CalculatorOutlined ,
  CalculatorTwoTone ,
  CalendarFilled ,
  CalendarOutlined ,
  CalendarTwoTone ,
  CameraFilled ,
  CameraOutlined ,
  CameraTwoTone ,
  CarFilled ,
  CarOutlined ,
  CarTwoTone ,
  CaretDownFilled ,
  CaretDownOutlined ,
  CaretLeftFilled ,
  CaretLeftOutlined ,
  CaretRightFilled ,
  CaretRightOutlined ,
  CaretUpFilled ,
  CaretUpOutlined ,
  CarryOutFilled ,
  CarryOutOutlined ,
  CarryOutTwoTone ,
  CheckCircleFilled ,
  CheckCircleOutlined ,
  CheckCircleTwoTone ,
  CheckOutlined ,
  CheckSquareFilled ,
  CheckSquareOutlined ,
  CheckSquareTwoTone ,
  ChromeFilled ,
  ChromeOutlined ,
  CiCircleFilled ,
  CiCircleOutlined ,
  CiCircleTwoTone ,
  CiOutlined ,
  CiTwoTone ,
  ClearOutlined ,
  ClockCircleFilled ,
  ClockCircleOutlined ,
  ClockCircleTwoTone ,
  CloseCircleFilled ,
  CloseCircleOutlined ,
  CloseCircleTwoTone ,
  CloseOutlined ,
  CloseSquareFilled ,
  CloseSquareOutlined ,
  CloseSquareTwoTone ,
  CloudDownloadOutlined ,
  CloudFilled ,
  CloudOutlined ,
  CloudServerOutlined ,
  CloudSyncOutlined ,
  CloudTwoTone ,
  CloudUploadOutlined ,
  ClusterOutlined ,
  CodeFilled ,
  CodeOutlined ,
  CodeSandboxCircleFilled ,
  CodeSandboxOutlined ,
  CodeSandboxSquareFilled ,
  CodeTwoTone ,
  CodepenCircleFilled ,
  CodepenCircleOutlined ,
  CodepenOutlined ,
  CodepenSquareFilled ,
  CoffeeOutlined ,
  ColumnHeightOutlined ,
  ColumnWidthOutlined ,
  CommentOutlined ,
  CompassFilled ,
  CompassOutlined ,
  CompassTwoTone ,
  CompressOutlined ,
  ConsoleSqlOutlined ,
  ContactsFilled ,
  ContactsOutlined ,
  ContactsTwoTone ,
  ContainerFilled ,
  ContainerOutlined ,
  ContainerTwoTone ,
  ControlFilled ,
  ControlOutlined ,
  ControlTwoTone ,
  CopyFilled ,
  CopyOutlined ,
  CopyTwoTone ,
  CopyrightCircleFilled ,
  CopyrightCircleOutlined ,
  CopyrightCircleTwoTone ,
  CopyrightOutlined ,
  CopyrightTwoTone ,
  CreditCardFilled ,
  CreditCardOutlined ,
  CreditCardTwoTone ,
  CrownFilled ,
  CrownOutlined ,
  CrownTwoTone ,
  CustomerServiceFilled ,
  CustomerServiceOutlined ,
  CustomerServiceTwoTone ,
  DashOutlined ,
  DashboardFilled ,
  DashboardOutlined ,
  DashboardTwoTone ,
  DatabaseFilled ,
  DatabaseOutlined ,
  DatabaseTwoTone ,
  DeleteColumnOutlined ,
  DeleteFilled ,
  DeleteOutlined ,
  DeleteRowOutlined ,
  DeleteTwoTone ,
  DeliveredProcedureOutlined ,
  DeploymentUnitOutlined ,
  DesktopOutlined ,
  DiffFilled ,
  DiffOutlined ,
  DiffTwoTone ,
  DingdingOutlined ,
  DingtalkCircleFilled ,
  DingtalkOutlined ,
  DingtalkSquareFilled ,
  DisconnectOutlined ,
  DislikeFilled ,
  DislikeOutlined ,
  DislikeTwoTone ,
  DollarCircleFilled ,
  DollarCircleOutlined ,
  DollarCircleTwoTone ,
  DollarOutlined ,
  DollarTwoTone ,
  DotChartOutlined ,
  DoubleLeftOutlined ,
  DoubleRightOutlined ,
  DownCircleFilled ,
  DownCircleOutlined ,
  DownCircleTwoTone ,
  DownOutlined ,
  DownSquareFilled ,
  DownSquareOutlined ,
  DownSquareTwoTone ,
  DownloadOutlined ,
  DragOutlined ,
  DribbbleCircleFilled ,
  DribbbleOutlined ,
  DribbbleSquareFilled ,
  DribbbleSquareOutlined ,
  DropboxCircleFilled ,
  DropboxOutlined ,
  DropboxSquareFilled ,
  EditFilled ,
  EditOutlined ,
  EditTwoTone ,
  EllipsisOutlined ,
  EnterOutlined ,
  EnvironmentFilled ,
  EnvironmentOutlined ,
  EnvironmentTwoTone ,
  EuroCircleFilled ,
  EuroCircleOutlined ,
  EuroCircleTwoTone ,
  EuroOutlined ,
  EuroTwoTone ,
  ExceptionOutlined ,
  ExclamationCircleFilled ,
  ExclamationCircleOutlined ,
  ExclamationCircleTwoTone ,
  ExclamationOutlined ,
  ExpandAltOutlined ,
  ExpandOutlined ,
  ExperimentFilled ,
  ExperimentOutlined ,
  ExperimentTwoTone ,
  ExportOutlined ,
  EyeFilled ,
  EyeInvisibleFilled ,
  EyeInvisibleOutlined ,
  EyeInvisibleTwoTone ,
  EyeOutlined ,
  EyeTwoTone ,
  FacebookFilled ,
  FacebookOutlined ,
  FallOutlined ,
  FastBackwardFilled ,
  FastBackwardOutlined ,
  FastForwardFilled ,
  FastForwardOutlined ,
  FieldBinaryOutlined ,
  FieldNumberOutlined ,
  FieldStringOutlined ,
  FieldTimeOutlined ,
  FileAddFilled ,
  FileAddOutlined ,
  FileAddTwoTone ,
  FileDoneOutlined ,
  FileExcelFilled ,
  FileExcelOutlined ,
  FileExcelTwoTone ,
  FileExclamationFilled ,
  FileExclamationOutlined ,
  FileExclamationTwoTone ,
  FileFilled ,
  FileGifOutlined ,
  FileImageFilled ,
  FileImageOutlined ,
  FileImageTwoTone ,
  FileJpgOutlined ,
  FileMarkdownFilled ,
  FileMarkdownOutlined ,
  FileMarkdownTwoTone ,
  FileOutlined ,
  FilePdfFilled ,
  FilePdfOutlined ,
  FilePdfTwoTone ,
  FilePptFilled ,
  FilePptOutlined ,
  FilePptTwoTone ,
  FileProtectOutlined ,
  FileSearchOutlined ,
  FileSyncOutlined ,
  FileTextFilled ,
  FileTextOutlined ,
  FileTextTwoTone ,
  FileTwoTone ,
  FileUnknownFilled ,
  FileUnknownOutlined ,
  FileUnknownTwoTone ,
  FileWordFilled ,
  FileWordOutlined ,
  FileWordTwoTone ,
  FileZipFilled ,
  FileZipOutlined ,
  FileZipTwoTone ,
  FilterFilled ,
  FilterOutlined ,
  FilterTwoTone ,
  FireFilled ,
  FireOutlined ,
  FireTwoTone ,
  FlagFilled ,
  FlagOutlined ,
  FlagTwoTone ,
  FolderAddFilled ,
  FolderAddOutlined ,
  FolderAddTwoTone ,
  FolderFilled ,
  FolderOpenFilled ,
  FolderOpenOutlined ,
  FolderOpenTwoTone ,
  FolderOutlined ,
  FolderTwoTone ,
  FolderViewOutlined ,
  FontColorsOutlined ,
  FontSizeOutlined ,
  ForkOutlined ,
  FormOutlined ,
  FormatPainterFilled ,
  FormatPainterOutlined ,
  ForwardFilled ,
  ForwardOutlined ,
  FrownFilled ,
  FrownOutlined ,
  FrownTwoTone ,
  FullscreenExitOutlined ,
  FullscreenOutlined ,
  FunctionOutlined ,
  FundFilled ,
  FundOutlined ,
  FundProjectionScreenOutlined ,
  FundTwoTone ,
  FundViewOutlined ,
  FunnelPlotFilled ,
  FunnelPlotOutlined ,
  FunnelPlotTwoTone ,
  GatewayOutlined ,
  GifOutlined ,
  GiftFilled ,
  GiftOutlined ,
  GiftTwoTone ,
  GithubFilled ,
  GithubOutlined ,
  GitlabFilled ,
  GitlabOutlined ,
  GlobalOutlined ,
  GoldFilled ,
  GoldOutlined ,
  GoldTwoTone ,
  GoldenFilled ,
  GoogleCircleFilled ,
  GoogleOutlined ,
  GooglePlusCircleFilled ,
  GooglePlusOutlined ,
  GooglePlusSquareFilled ,
  GoogleSquareFilled ,
  GroupOutlined ,
  HddFilled ,
  HddOutlined ,
  HddTwoTone ,
  HeartFilled ,
  HeartOutlined ,
  HeartTwoTone ,
  HeatMapOutlined ,
  HighlightFilled ,
  HighlightOutlined ,
  HighlightTwoTone ,
  HistoryOutlined ,
  HolderOutlined ,
  HomeFilled ,
  HomeOutlined ,
  HomeTwoTone ,
  HourglassFilled ,
  HourglassOutlined ,
  HourglassTwoTone ,
  Html5Filled ,
  Html5Outlined ,
  Html5TwoTone ,
  IdcardFilled ,
  IdcardOutlined ,
  IdcardTwoTone ,
  IeCircleFilled ,
  IeOutlined ,
  IeSquareFilled ,
  ImportOutlined ,
  InboxOutlined ,
  InfoCircleFilled ,
  InfoCircleOutlined ,
  InfoCircleTwoTone ,
  InfoOutlined ,
  InsertRowAboveOutlined ,
  InsertRowBelowOutlined ,
  InsertRowLeftOutlined ,
  InsertRowRightOutlined ,
  InstagramFilled ,
  InstagramOutlined ,
  InsuranceFilled ,
  InsuranceOutlined ,
  InsuranceTwoTone ,
  InteractionFilled ,
  InteractionOutlined ,
  InteractionTwoTone ,
  IssuesCloseOutlined ,
  ItalicOutlined ,
  KeyOutlined ,
  LaptopOutlined ,
  LayoutFilled ,
  LayoutOutlined ,
  LayoutTwoTone ,
  LeftCircleFilled ,
  LeftCircleOutlined ,
  LeftCircleTwoTone ,
  LeftOutlined ,
  LeftSquareFilled ,
  LeftSquareOutlined ,
  LeftSquareTwoTone ,
  LikeFilled ,
  LikeOutlined ,
  LikeTwoTone ,
  LineChartOutlined ,
  LineHeightOutlined ,
  LineOutlined ,
  LinkOutlined ,
  LinkedinFilled ,
  LinkedinOutlined ,
  Loading3QuartersOutlined ,
  LoadingOutlined ,
  LockFilled ,
  LockOutlined ,
  LockTwoTone ,
  LoginOutlined ,
  LogoutOutlined ,
  MacCommandFilled ,
  MacCommandOutlined ,
  MailFilled ,
  MailOutlined ,
  MailTwoTone ,
  ManOutlined ,
  MedicineBoxFilled ,
  MedicineBoxOutlined ,
  MedicineBoxTwoTone ,
  MediumCircleFilled ,
  MediumOutlined ,
  MediumSquareFilled ,
  MediumWorkmarkOutlined ,
  MehFilled ,
  MehOutlined ,
  MehTwoTone ,
  MenuFoldOutlined ,
  MenuOutlined ,
  MenuUnfoldOutlined ,
  MergeCellsOutlined ,
  MessageFilled ,
  MessageOutlined ,
  MessageTwoTone ,
  MinusCircleFilled ,
  MinusCircleOutlined ,
  MinusCircleTwoTone ,
  MinusOutlined ,
  MinusSquareFilled ,
  MinusSquareOutlined ,
  MinusSquareTwoTone ,
  MobileFilled ,
  MobileOutlined ,
  MobileTwoTone ,
  MoneyCollectFilled ,
  MoneyCollectOutlined ,
  MoneyCollectTwoTone ,
  MonitorOutlined ,
  MoreOutlined ,
  NodeCollapseOutlined ,
  NodeExpandOutlined ,
  NodeIndexOutlined ,
  NotificationFilled ,
  NotificationOutlined ,
  NotificationTwoTone ,
  NumberOutlined ,
  OneToOneOutlined ,
  OrderedListOutlined ,
  PaperClipOutlined ,
  PartitionOutlined ,
  PauseCircleFilled ,
  PauseCircleOutlined ,
  PauseCircleTwoTone ,
  PauseOutlined ,
  PayCircleFilled ,
  PayCircleOutlined ,
  PercentageOutlined ,
  PhoneFilled ,
  PhoneOutlined ,
  PhoneTwoTone ,
  PicCenterOutlined ,
  PicLeftOutlined ,
  PicRightOutlined ,
  PictureFilled ,
  PictureOutlined ,
  PictureTwoTone ,
  PieChartFilled ,
  PieChartOutlined ,
  PieChartTwoTone ,
  PlayCircleFilled ,
  PlayCircleOutlined ,
  PlayCircleTwoTone ,
  PlaySquareFilled ,
  PlaySquareOutlined ,
  PlaySquareTwoTone ,
  PlusCircleFilled ,
  PlusCircleOutlined ,
  PlusCircleTwoTone ,
  PlusOutlined ,
  PlusSquareFilled ,
  PlusSquareOutlined ,
  PlusSquareTwoTone ,
  PoundCircleFilled ,
  PoundCircleOutlined ,
  PoundCircleTwoTone ,
  PoundOutlined ,
  PoweroffOutlined ,
  PrinterFilled ,
  PrinterOutlined ,
  PrinterTwoTone ,
  ProfileFilled ,
  ProfileOutlined ,
  ProfileTwoTone ,
  ProjectFilled ,
  ProjectOutlined ,
  ProjectTwoTone ,
  PropertySafetyFilled ,
  PropertySafetyOutlined ,
  PropertySafetyTwoTone ,
  PullRequestOutlined ,
  PushpinFilled ,
  PushpinOutlined ,
  PushpinTwoTone ,
  QqCircleFilled ,
  QqOutlined ,
  QqSquareFilled ,
  QrcodeOutlined ,
  QuestionCircleFilled ,
  QuestionCircleOutlined ,
  QuestionCircleTwoTone ,
  QuestionOutlined ,
  RadarChartOutlined ,
  RadiusBottomleftOutlined ,
  RadiusBottomrightOutlined ,
  RadiusSettingOutlined ,
  RadiusUpleftOutlined ,
  RadiusUprightOutlined ,
  ReadFilled ,
  ReadOutlined ,
  ReconciliationFilled ,
  ReconciliationOutlined ,
  ReconciliationTwoTone ,
  RedEnvelopeFilled ,
  RedEnvelopeOutlined ,
  RedEnvelopeTwoTone ,
  RedditCircleFilled ,
  RedditOutlined ,
  RedditSquareFilled ,
  RedoOutlined ,
  ReloadOutlined ,
  RestFilled ,
  RestOutlined ,
  RestTwoTone ,
  RetweetOutlined ,
  RightCircleFilled ,
  RightCircleOutlined ,
  RightCircleTwoTone ,
  RightOutlined ,
  RightSquareFilled ,
  RightSquareOutlined ,
  RightSquareTwoTone ,
  RiseOutlined ,
  RobotFilled ,
  RobotOutlined ,
  RocketFilled ,
  RocketOutlined ,
  RocketTwoTone ,
  RollbackOutlined ,
  RotateLeftOutlined ,
  RotateRightOutlined ,
  SafetyCertificateFilled ,
  SafetyCertificateOutlined ,
  SafetyCertificateTwoTone ,
  SafetyOutlined ,
  SaveFilled ,
  SaveOutlined ,
  SaveTwoTone ,
  ScanOutlined ,
  ScheduleFilled ,
  ScheduleOutlined ,
  ScheduleTwoTone ,
  ScissorOutlined ,
  SearchOutlined ,
  SecurityScanFilled ,
  SecurityScanOutlined ,
  SecurityScanTwoTone ,
  SelectOutlined ,
  SendOutlined ,
  SettingFilled ,
  SettingOutlined ,
  SettingTwoTone ,
  ShakeOutlined ,
  ShareAltOutlined ,
  ShopFilled ,
  ShopOutlined ,
  ShopTwoTone ,
  ShoppingCartOutlined ,
  ShoppingFilled ,
  ShoppingOutlined ,
  ShoppingTwoTone ,
  ShrinkOutlined ,
  SignalFilled ,
  SisternodeOutlined ,
  SketchCircleFilled ,
  SketchOutlined ,
  SketchSquareFilled ,
  SkinFilled ,
  SkinOutlined ,
  SkinTwoTone ,
  SkypeFilled ,
  SkypeOutlined ,
  SlackCircleFilled ,
  SlackOutlined ,
  SlackSquareFilled ,
  SlackSquareOutlined ,
  SlidersFilled ,
  SlidersOutlined ,
  SlidersTwoTone ,
  SmallDashOutlined ,
  SmileFilled ,
  SmileOutlined ,
  SmileTwoTone ,
  SnippetsFilled ,
  SnippetsOutlined ,
  SnippetsTwoTone ,
  SolutionOutlined ,
  SortAscendingOutlined ,
  SortDescendingOutlined ,
  SoundFilled ,
  SoundOutlined ,
  SoundTwoTone ,
  SplitCellsOutlined ,
  StarFilled ,
  StarOutlined ,
  StarTwoTone ,
  StepBackwardFilled ,
  StepBackwardOutlined ,
  StepForwardFilled ,
  StepForwardOutlined ,
  StockOutlined ,
  StopFilled ,
  StopOutlined ,
  StopTwoTone ,
  StrikethroughOutlined ,
  SubnodeOutlined ,
  SwapLeftOutlined ,
  SwapOutlined ,
  SwapRightOutlined ,
  SwitcherFilled ,
  SwitcherOutlined ,
  SwitcherTwoTone ,
  SyncOutlined ,
  TableOutlined ,
  TabletFilled ,
  TabletOutlined ,
  TabletTwoTone ,
  TagFilled ,
  TagOutlined ,
  TagTwoTone ,
  TagsFilled ,
  TagsOutlined ,
  TagsTwoTone ,
  TaobaoCircleFilled ,
  TaobaoCircleOutlined ,
  TaobaoOutlined ,
  TaobaoSquareFilled ,
  TeamOutlined ,
  ThunderboltFilled ,
  ThunderboltOutlined ,
  ThunderboltTwoTone ,
  ToTopOutlined ,
  ToolFilled ,
  ToolOutlined ,
  ToolTwoTone ,
  TrademarkCircleFilled ,
  TrademarkCircleOutlined ,
  TrademarkCircleTwoTone ,
  TrademarkOutlined ,
  TransactionOutlined ,
  TranslationOutlined ,
  TrophyFilled ,
  TrophyOutlined ,
  TrophyTwoTone ,
  TwitterCircleFilled ,
  TwitterOutlined ,
  TwitterSquareFilled ,
  UnderlineOutlined ,
  UndoOutlined ,
  UngroupOutlined ,
  UnlockFilled ,
  UnlockOutlined ,
  UnlockTwoTone ,
  UnorderedListOutlined ,
  UpCircleFilled ,
  UpCircleOutlined ,
  UpCircleTwoTone ,
  UpOutlined ,
  UpSquareFilled ,
  UpSquareOutlined ,
  UpSquareTwoTone ,
  UploadOutlined ,
  UsbFilled ,
  UsbOutlined ,
  UsbTwoTone ,
  UserAddOutlined ,
  UserDeleteOutlined ,
  UserOutlined ,
  UserSwitchOutlined ,
  UsergroupAddOutlined ,
  UsergroupDeleteOutlined ,
  VerifiedOutlined ,
  VerticalAlignBottomOutlined ,
  VerticalAlignMiddleOutlined ,
  VerticalAlignTopOutlined ,
  VerticalLeftOutlined ,
  VerticalRightOutlined ,
  VideoCameraAddOutlined ,
  VideoCameraFilled ,
  VideoCameraOutlined ,
  VideoCameraTwoTone ,
  WalletFilled ,
  WalletOutlined ,
  WalletTwoTone ,
  WarningFilled ,
  WarningOutlined ,
  WarningTwoTone ,
  WechatFilled ,
  WechatOutlined ,
  WeiboCircleFilled ,
  WeiboCircleOutlined ,
  WeiboOutlined ,
  WeiboSquareFilled ,
  WeiboSquareOutlined ,
  WhatsAppOutlined ,
  WifiOutlined ,
  WindowsFilled ,
  WindowsOutlined ,
  WomanOutlined ,
  YahooFilled ,
  YahooOutlined ,
  YoutubeFilled ,
  YoutubeOutlined ,
  YuqueFilled ,
  YuqueOutlined ,
  ZhihuCircleFilled ,
  ZhihuOutlined ,
  ZhihuSquareFilled ,
  ZoomInOutlined ,
  ZoomOutOutlined ,
  
}
/* No side effect */
