// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var isString = (function(c) { return typeof c === 'string' });

var isNumber = (function(c) { return typeof c === 'number' });

var Children = {
  isString: isString,
  isNumber: isNumber
};

function MxRC__Libs__React$Partal(Props) {
  var getContainer = Props.getContainer;
  var children = Props.children;
  var children$1 = Belt_Option.getWithDefault(children, null);
  var containerRef = React.useRef(undefined);
  var initRef = React.useRef(false);
  if (!initRef.current) {
    initRef.current = true;
    containerRef.current = Caml_option.some(Curry._1(getContainer, undefined));
  }
  console.log("partal render", containerRef.current, children$1);
  if (Belt_Option.isSome(containerRef.current)) {
    return ReactDom.createPortal(children$1, containerRef.current);
  } else {
    return null;
  }
}

var Partal = {
  make: MxRC__Libs__React$Partal
};

export {
  Children ,
  Partal ,
  
}
/* react Not a pure module */
