// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ExternalsJs from "./_externals.js";

function makeBreakpointNumberHash(prim) {
  return ExternalsJs.makeBreakpointNumberHash(prim);
}

function makeBreakpointNumberHashArray(prim) {
  return ExternalsJs.makeBreakpointNumberHashArray(prim);
}

function getCurrentBreakpointValue(prim0, prim1) {
  return ExternalsJs.getCurrentBreakpointValue(prim0, prim1);
}

var BreakpointUtils = {
  makeBreakpointNumberHash: makeBreakpointNumberHash,
  makeBreakpointNumberHashArray: makeBreakpointNumberHashArray,
  getCurrentBreakpointValue: getCurrentBreakpointValue
};

export {
  BreakpointUtils ,
  
}
/* ./_externals.js Not a pure module */
