// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TwindJs from "./__twind.js";

var conf = TwindJs.conf;

import * as c from 'twind/colors'
;

var colors = c;

export {
  conf ,
  colors ,
  
}
/* conf Not a pure module */
