// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Twind from "twind";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MxRC__Libs__Twind from "./libs/MxRC__Libs__Twind.js";

var ctx = React.createContext({
      size: "default"
    });

var provider = ctx.Provider;

function MxRC__ConfigProvider$ConfigContext$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: MxRC__ConfigProvider$ConfigContext$Provider
};

var ConfigContext = {
  ctx: ctx,
  Provider: Provider
};

var b = MxRC__Libs__Twind.colors.blue;

var r = MxRC__Libs__Twind.colors.red;

var colors_primary = {
  base: b[500],
  hover: b[400],
  active: b[600]
};

var colors_link = {
  base: b[500],
  hover: b[400],
  active: b[600]
};

var colors_danger = {
  base: r[500],
  hover: r[400],
  active: r[600]
};

var colors = {
  primary: colors_primary,
  link: colors_link,
  danger: colors_danger
};

function init(primary, param) {
  Twind.setup({
        preflight: {
          ":root": {
            "--color-primary": Belt_Option.getWithDefault(primary, colors_primary.base),
            "--color-primary-hover": colors_primary.hover,
            "--color-primary-active": colors_primary.active,
            "--color-link": colors_link.base,
            "--color-link-hover": colors_link.hover,
            "--color-link-active": colors_link.active,
            "--color-danger": colors_danger.base,
            "--color-danger-hover": colors_danger.hover,
            "--color-danger-active": colors_danger.active
          },
          "button:focus": {
            outline: "0"
          }
        },
        theme: {
          colors: {
            initial: "initial",
            inherit: "inherit",
            transparent: "transparent",
            text: {
              DEFAULT: "rgba(0, 0, 0, .85)"
            },
            link: {
              DEFAULT: "var(--color-link)",
              hover: "var(--color-link-hover)",
              active: "var(--color-link-active)"
            },
            primary: {
              DEFAULT: "var(--color-primary)",
              hover: "var(--color-primary-hover)",
              active: "var(--color-primary-active)"
            },
            danger: {
              DEFAULT: "var(--color-danger)",
              hover: "var(--color-danger-hover)",
              active: "var(--color-danger-active)"
            }
          },
          transitionTimingFunction: {
            DEFAULT: "cubic-bezier(.645,.045,.355,1)"
          },
          fontSize: {
            base: ['14px', { 'lineHeight': '22px' }],
            lg: ['16px', { 'lineHeight': '24px' }]
          },
          extend: {
            colors: MxRC__Libs__Twind.colors
          }
        }
      });
  
}

init(undefined, undefined);

function MxRC__ConfigProvider(Props) {
  var sizeOpt = Props.size;
  var childrenOpt = Props.children;
  var size = sizeOpt !== undefined ? sizeOpt : "default";
  var children = childrenOpt !== undefined ? Caml_option.valFromOption(childrenOpt) : null;
  var value = React.useMemo((function () {
          return {
                  size: size
                };
        }), [size]);
  return React.createElement(React.Fragment, undefined, React.createElement(MxRC__ConfigProvider$ConfigContext$Provider, {
                  value: value,
                  children: children
                }));
}

var make = MxRC__ConfigProvider;

export {
  ConfigContext ,
  colors ,
  init ,
  make ,
  
}
/* ctx Not a pure module */
