// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Twind from "twind";
import * as Css from "twind/css";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as MxRC__Libs__React from "../_libs/MxRC__Libs__React.bs.js";
import * as MxRC__Libs__Twind from "../_libs/MxRC__Libs__Twind.bs.js";

function makeOut($$class) {
  return MxRC__Libs__Twind.atw($$class, ["inline-block"]);
}

function makeIn($$class) {
  var classes = [
    "table w-full m-0 p-0 tabular-nums",
    Css.css({
          "& > *:first-child": Twind.apply(["rounded-l"]),
          "& > *:last-child": Twind.apply(["rounded-r"]),
          "& > *:not(:first-child)": Twind.apply(["rounded-l-none"]),
          "& > *:not(:last-child)": Twind.apply(["rounded-r-none"]),
          "& > *": Twind.apply(["table-cell align-middle"])
        })
  ];
  return MxRC__Libs__Twind.atw($$class, classes);
}

function makeAddon(isStandard) {
  var classes = [
    "relative font-normal transition",
    isStandard ? "px-3-bordered text(sm center text) bg(background) border(1 border)" : "-left-px",
    Css.css({
          "&:first-child": Twind.apply(["border-r-0"]),
          "&:last-child": Twind.apply(["border-l-0"])
        })
  ];
  return MxRC__Libs__Twind.atw(undefined, classes);
}

var InputGroupTwind = {
  makeOut: makeOut,
  makeIn: makeIn,
  makeAddon: makeAddon
};

function MxRC__Input__Group$InputGroupAddon(Props) {
  var children = Props.children;
  var children$1 = Belt_Option.getWithDefault(children, null);
  var isStandard = MxRC__Libs__React.Children.isString(children$1);
  return React.createElement("span", {
              className: makeAddon(isStandard)
            }, children$1);
}

var InputGroupAddon = {
  make: MxRC__Input__Group$InputGroupAddon
};

function MxRC__Input__Group(Props) {
  var className = Props.className;
  var innerClassName = Props.innerClassName;
  var children = Props.children;
  var children$1 = Belt_Option.getWithDefault(children, null);
  return React.createElement("span", {
              className: MxRC__Libs__Twind.atw(className, ["inline-block"])
            }, React.createElement("span", {
                  className: makeIn(innerClassName)
                }, children$1));
}

var make = MxRC__Input__Group;

export {
  InputGroupTwind ,
  InputGroupAddon ,
  make ,
  
}
/* react Not a pure module */
