// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function MxRC__Input__Affix$InputAffixAddon(Props) {
  var children = Props.children;
  var children$1 = Belt_Option.getWithDefault(children, null);
  return React.createElement("span", undefined, children$1);
}

var InputAffixAddon = {
  make: MxRC__Input__Affix$InputAffixAddon
};

function MxRC__Input__Affix(Props) {
  var className = Props.className;
  var children = Props.children;
  var children$1 = Belt_Option.getWithDefault(children, null);
  var tmp = {};
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("span", tmp, children$1);
}

var make = MxRC__Input__Affix;

export {
  InputAffixAddon ,
  make ,
  
}
/* react Not a pure module */
