// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MxRC__Input__Twind from "./MxRC__Input__Twind.bs.js";
import * as MxRC__ConfigProvider from "../config-provider/MxRC__ConfigProvider.bs.js";

function MxRC__Input__TextArea(Props) {
  var size = Props.size;
  var className = Props.className;
  var rows = Props.rows;
  var context = React.useContext(MxRC__ConfigProvider.ConfigContext.ctx);
  var size$1 = Belt_Option.getWithDefault(size, context.size);
  var className$1 = MxRC__Input__Twind.makeTextArea(className, size$1, false);
  var tmp = {
    className: className$1
  };
  if (rows !== undefined) {
    tmp.rows = Caml_option.valFromOption(rows);
  }
  return React.createElement("textarea", tmp);
}

var Twind;

var make = MxRC__Input__TextArea;

export {
  Twind ,
  make ,
  
}
/* react Not a pure module */
