// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MxRC__Libs__Twind from "../_libs/MxRC__Libs__Twind.bs.js";

function makeInputBox($$class, size, z, flex) {
  var classes = ["\n    inline-block\n    relative\n    m-0\n    min-w-0\n    w-full\n    overflow-visible\n    text(sm text)\n    border(1 solid border)\n    hover:(border-primary-hover)\n    focus:(border-primary-hover shadow-input-focus)\n    transition\n    tabular-nums\n    rounded\n  "];
  if (flex) {
    classes.push("inline-flex");
  }
  classes.push(size === "small" ? "h-6 px-2-bordered" : (
          size === "default" ? "h-8 px-3-bordered" : "h-10 px-3-bordered text-base"
        ));
  if (z) {
    classes.push("z-1");
  }
  return MxRC__Libs__Twind.atw($$class, classes);
}

function makeFixed(pos) {
  var classes = ["flex flex-none items-center"];
  classes.push(pos === "prefix" ? "ml-1" : "mr-1");
  return MxRC__Libs__Twind.atw(undefined, classes);
}

export {
  makeInputBox ,
  makeFixed ,
  
}
/* MxRC__Libs__Twind Not a pure module */
