// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MxRC__Input from "./MxRC__Input.bs.js";
import * as MxRC__Button from "../button/MxRC__Button.bs.js";
import * as Icons from "@ant-design/icons";

function make(className, size, inGroup) {
  
}

var InputSearchTwind = {
  make: make
};

function MxRC__Input__Search(Props) {
  var size = Props.size;
  var className = Props.className;
  var style = Props.style;
  var placeholder = Props.placeholder;
  var addonBefore = Props.addonBefore;
  var addonAfter = React.createElement(MxRC__Button.make, {
        icon: React.createElement(Icons.SearchOutlined, {})
      });
  var tmp = {
    addonAfter: addonAfter
  };
  if (size !== undefined) {
    tmp.size = Caml_option.valFromOption(size);
  }
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  if (placeholder !== undefined) {
    tmp.placeholder = Caml_option.valFromOption(placeholder);
  }
  if (addonBefore !== undefined) {
    tmp.addonBefore = Caml_option.valFromOption(addonBefore);
  }
  return React.createElement(MxRC__Input.make, tmp);
}

var Input;

var Button;

var make$1 = MxRC__Input__Search;

export {
  Input ,
  Button ,
  InputSearchTwind ,
  make$1 as make,
  
}
/* react Not a pure module */
