// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MxRC__Input from "./MxRC__Input.bs.js";

function MxRC__Input__Password(Props) {
  return React.createElement(MxRC__Input.make, {});
}

var Input;

var make = MxRC__Input__Password;

export {
  Input ,
  make ,
  
}
/* react Not a pure module */
