// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MxRC__Input from "./MxRC__Input.bs.js";

function MxRC__Input__Password(Props) {
  var placeholder = Props.placeholder;
  var tmp = {};
  if (placeholder !== undefined) {
    tmp.placeholder = Caml_option.valFromOption(placeholder);
  }
  return React.createElement(MxRC__Input.make, tmp);
}

var Input;

var make = MxRC__Input__Password;

export {
  Input ,
  make ,
  
}
/* react Not a pure module */
