// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MxRC__Input from "./MxRC__Input.bs.js";
import * as Icons from "@ant-design/icons";

function MxRC__Input__Password(Props) {
  var placeholder = Props.placeholder;
  var disabled = Props.disabled;
  var match = React.useState(function () {
        return false;
      });
  var set = match[1];
  var visible = match[0];
  var onMouseDown = function ($$event) {
    $$event.preventDefault();
    
  };
  var onMouseUp = function ($$event) {
    $$event.preventDefault();
    
  };
  var onClick = function (param) {
    return Curry._1(set, (function (prev) {
                  return !prev;
                }));
  };
  var suffix = visible ? React.createElement(Icons.EyeOutlined, {
          onMouseUp: onMouseUp,
          onMouseDown: onMouseDown,
          onClick: onClick
        }) : React.createElement(Icons.EyeInvisibleOutlined, {
          onMouseUp: onMouseUp,
          onMouseDown: onMouseDown,
          onClick: onClick
        });
  var tmp = {
    type: visible ? "text" : "password",
    suffix: suffix,
    disabled: disabled
  };
  if (placeholder !== undefined) {
    tmp.placeholder = Caml_option.valFromOption(placeholder);
  }
  return React.createElement(MxRC__Input.make, tmp);
}

var Input;

var make = MxRC__Input__Password;

export {
  Input ,
  make ,
  
}
/* react Not a pure module */
