// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Id from "rescript/lib/es6/belt_Id.js";
import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_MutableMapInt from "rescript/lib/es6/belt_MutableMapInt.js";
import * as Belt_MutableMapString from "rescript/lib/es6/belt_MutableMapString.js";

var breakpoints = [
  "xxl",
  "xl",
  "lg",
  "md",
  "sm",
  "xs"
];

var cmp = Caml_obj.caml_compare;

var BreakpointCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

var queries = Belt_Map.fromArray([
      [
        "xs",
        "(max-width: 575px)"
      ],
      [
        "sm",
        "(min-width: 576px)"
      ],
      [
        "md",
        "(min-width: 768px)"
      ],
      [
        "lg",
        "(min-width: 992px)"
      ],
      [
        "xl",
        "(min-width: 1200px)"
      ],
      [
        "xxl",
        "(min-width: 1600px)"
      ]
    ], BreakpointCmp);

var screens = Belt_Map.fromArray([
      [
        "xs",
        false
      ],
      [
        "sm",
        false
      ],
      [
        "md",
        false
      ],
      [
        "lg",
        false
      ],
      [
        "xl",
        false
      ],
      [
        "xxl",
        false
      ]
    ], BreakpointCmp);

var token = {
  contents: -1
};

var store = Belt_MutableMapString.fromArray([]);

var subscribers = Belt_MutableMapInt.fromArray([]);

function register(param) {
  return Belt_Map.forEach(queries, (function (breakpoint, query) {
                var handler = function (evt) {
                  var matches = evt.matches;
                  Belt_Map.set(screens, breakpoint, matches);
                  return Belt_MutableMapInt.forEach(subscribers, (function (param, func) {
                                return Curry._1(func, screens);
                              }));
                };
                var mediaQueryList = window.matchMedia(query);
                mediaQueryList.addEventListener("change", handler);
                handler(mediaQueryList);
                return Belt_MutableMapString.set(store, query, {
                            mediaQueryList: mediaQueryList,
                            handler: handler
                          });
              }));
}

function unregister(param) {
  Belt_Map.forEach(queries, (function (param, query) {
          return Belt_Option.forEach(Belt_MutableMapString.get(store, query), (function (cached) {
                        cached.mediaQueryList.addEventListener("change", cached.handler);
                        
                      }));
        }));
  return Belt_MutableMapInt.clear(subscribers);
}

function subscribe(func) {
  if (Belt_MutableMapInt.size(subscribers) === 0) {
    register(undefined);
  }
  token.contents = token.contents + 1 | 0;
  Belt_MutableMapInt.set(subscribers, token.contents, func);
  Curry._1(func, screens);
  return token.contents;
}

function unsubscribe(id) {
  Belt_MutableMapInt.remove(subscribers, id);
  if (Belt_MutableMapInt.size(subscribers) === 0) {
    return unregister(undefined);
  }
  
}

export {
  breakpoints ,
  BreakpointCmp ,
  queries ,
  screens ,
  token ,
  store ,
  subscribers ,
  register ,
  unregister ,
  subscribe ,
  unsubscribe ,
  
}
/* BreakpointCmp Not a pure module */
