// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Webapi__Dom from "rescript-webapi/src/Webapi/Webapi__Dom.js";
import * as Webapi__Dom__Element from "rescript-webapi/src/Webapi/Dom/Webapi__Dom__Element.js";

var MxElement = Webapi__Dom__Element;

var ChangeEvent = {};

var $$MediaQueryList = {
  ChangeEvent: ChangeEvent
};

var $$AnimationEvent = Webapi__Dom.$$AnimationEvent;

var $$Attr = Webapi__Dom.$$Attr;

var $$BeforeUnloadEvent = Webapi__Dom.$$BeforeUnloadEvent;

var CdataSection = Webapi__Dom.CdataSection;

var $$CharacterData = Webapi__Dom.$$CharacterData;

var $$ClipboardEvent = Webapi__Dom.$$ClipboardEvent;

var $$CloseEvent = Webapi__Dom.$$CloseEvent;

var $$Comment = Webapi__Dom.$$Comment;

var $$CompositionEvent = Webapi__Dom.$$CompositionEvent;

var CssStyleDeclaration = Webapi__Dom.CssStyleDeclaration;

var $$CustomEvent = Webapi__Dom.$$CustomEvent;

var $$DataTransfer = Webapi__Dom.$$DataTransfer;

var $$DataTransferItem = Webapi__Dom.$$DataTransferItem;

var $$DataTransferItemList = Webapi__Dom.$$DataTransferItemList;

var $$Document = Webapi__Dom.$$Document;

var $$DocumentFragment = Webapi__Dom.$$DocumentFragment;

var $$DocumentType = Webapi__Dom.$$DocumentType;

var DomImplementation = Webapi__Dom.DomImplementation;

var DomRect = Webapi__Dom.DomRect;

var DomStringMap = Webapi__Dom.DomStringMap;

var DomTokenList = Webapi__Dom.DomTokenList;

var $$DragEvent = Webapi__Dom.$$DragEvent;

var $$Element = Webapi__Dom.$$Element;

var $$ErrorEvent = Webapi__Dom.$$ErrorEvent;

var $$Event = Webapi__Dom.$$Event;

var $$EventTarget = Webapi__Dom.$$EventTarget;

var $$FocusEvent = Webapi__Dom.$$FocusEvent;

var $$History = Webapi__Dom.$$History;

var HtmlButtonElement = Webapi__Dom.HtmlButtonElement;

var HtmlCollection = Webapi__Dom.HtmlCollection;

var HtmlDocument = Webapi__Dom.HtmlDocument;

var HtmlElement = Webapi__Dom.HtmlElement;

var HtmlFieldSetElement = Webapi__Dom.HtmlFieldSetElement;

var HtmlFormControlsCollection = Webapi__Dom.HtmlFormControlsCollection;

var HtmlFormElement = Webapi__Dom.HtmlFormElement;

var HtmlImageElement = Webapi__Dom.HtmlImageElement;

var HtmlInputElement = Webapi__Dom.HtmlInputElement;

var HtmlObjectElement = Webapi__Dom.HtmlObjectElement;

var HtmlOptGroupElement = Webapi__Dom.HtmlOptGroupElement;

var HtmlOptionElement = Webapi__Dom.HtmlOptionElement;

var HtmlOptionsCollection = Webapi__Dom.HtmlOptionsCollection;

var HtmlOutputElement = Webapi__Dom.HtmlOutputElement;

var HtmlSelectElement = Webapi__Dom.HtmlSelectElement;

var HtmlTextAreaElement = Webapi__Dom.HtmlTextAreaElement;

var IdbVersionChangeEvent = Webapi__Dom.IdbVersionChangeEvent;

var $$Image = Webapi__Dom.$$Image;

var $$InputEvent = Webapi__Dom.$$InputEvent;

var $$KeyboardEvent = Webapi__Dom.$$KeyboardEvent;

var $$Location = Webapi__Dom.$$Location;

var $$MouseEvent = Webapi__Dom.$$MouseEvent;

var $$MutationObserver = Webapi__Dom.$$MutationObserver;

var $$MutationRecord = Webapi__Dom.$$MutationRecord;

var $$NamedNodeMap = Webapi__Dom.$$NamedNodeMap;

var $$Node = Webapi__Dom.$$Node;

var $$NodeFilter = Webapi__Dom.$$NodeFilter;

var $$NodeIterator = Webapi__Dom.$$NodeIterator;

var $$NodeList = Webapi__Dom.$$NodeList;

var $$PageTransitionEvent = Webapi__Dom.$$PageTransitionEvent;

var $$PointerEvent = Webapi__Dom.$$PointerEvent;

var $$PopStateEvent = Webapi__Dom.$$PopStateEvent;

var $$ProcessingInstruction = Webapi__Dom.$$ProcessingInstruction;

var $$ProgressEvent = Webapi__Dom.$$ProgressEvent;

var $$RadioNodeList = Webapi__Dom.$$RadioNodeList;

var $$Range = Webapi__Dom.$$Range;

var RectList = Webapi__Dom.RectList;

var RelatedEvent = Webapi__Dom.RelatedEvent;

var $$Selection = Webapi__Dom.$$Selection;

var $$ShadowRoot = Webapi__Dom.$$ShadowRoot;

var $$StaticRange = Webapi__Dom.$$StaticRange;

var $$StorageEvent = Webapi__Dom.$$StorageEvent;

var SvgZoomEvent = Webapi__Dom.SvgZoomEvent;

var $$Text = Webapi__Dom.$$Text;

var TimeEvent = Webapi__Dom.TimeEvent;

var $$TouchEvent = Webapi__Dom.$$TouchEvent;

var $$TrackEvent = Webapi__Dom.$$TrackEvent;

var $$TransitionEvent = Webapi__Dom.$$TransitionEvent;

var $$TreeWalker = Webapi__Dom.$$TreeWalker;

var UiEvent = Webapi__Dom.UiEvent;

var $$ValidityState = Webapi__Dom.$$ValidityState;

var WebGlContextEvent = Webapi__Dom.WebGlContextEvent;

var $$WheelEvent = Webapi__Dom.$$WheelEvent;

var $$Window = Webapi__Dom.$$Window;

var encodeCompareHow = Webapi__Dom.encodeCompareHow;

var decodeCompareResult = Webapi__Dom.decodeCompareResult;

var decodeCompatMode = Webapi__Dom.decodeCompatMode;

var encodeContentEditable = Webapi__Dom.encodeContentEditable;

var decodeContentEditable = Webapi__Dom.decodeContentEditable;

var decodeDeltaMode = Webapi__Dom.decodeDeltaMode;

var encodeDesignMode = Webapi__Dom.encodeDesignMode;

var decodeDesignMode = Webapi__Dom.decodeDesignMode;

var encodeDir = Webapi__Dom.encodeDir;

var decodeDir = Webapi__Dom.decodeDir;

var EventPhase = Webapi__Dom.EventPhase;

var encodeFilterAction = Webapi__Dom.encodeFilterAction;

var encodeInsertPosition = Webapi__Dom.encodeInsertPosition;

var encodeModifierKey = Webapi__Dom.encodeModifierKey;

var decodeNodeType = Webapi__Dom.decodeNodeType;

var decodePointerType = Webapi__Dom.decodePointerType;

var decodeReadyState = Webapi__Dom.decodeReadyState;

var decodeShadowRootMode = Webapi__Dom.decodeShadowRootMode;

var decodeVisibilityState = Webapi__Dom.decodeVisibilityState;

var WhatToShow = Webapi__Dom.WhatToShow;

export {
  $$AnimationEvent ,
  $$Attr ,
  $$BeforeUnloadEvent ,
  CdataSection ,
  $$CharacterData ,
  $$ClipboardEvent ,
  $$CloseEvent ,
  $$Comment ,
  $$CompositionEvent ,
  CssStyleDeclaration ,
  $$CustomEvent ,
  $$DataTransfer ,
  $$DataTransferItem ,
  $$DataTransferItemList ,
  $$Document ,
  $$DocumentFragment ,
  $$DocumentType ,
  DomImplementation ,
  DomRect ,
  DomStringMap ,
  DomTokenList ,
  $$DragEvent ,
  $$Element ,
  $$ErrorEvent ,
  $$Event ,
  $$EventTarget ,
  $$FocusEvent ,
  $$History ,
  HtmlButtonElement ,
  HtmlCollection ,
  HtmlDocument ,
  HtmlElement ,
  HtmlFieldSetElement ,
  HtmlFormControlsCollection ,
  HtmlFormElement ,
  HtmlImageElement ,
  HtmlInputElement ,
  HtmlObjectElement ,
  HtmlOptGroupElement ,
  HtmlOptionElement ,
  HtmlOptionsCollection ,
  HtmlOutputElement ,
  HtmlSelectElement ,
  HtmlTextAreaElement ,
  IdbVersionChangeEvent ,
  $$Image ,
  $$InputEvent ,
  $$KeyboardEvent ,
  $$Location ,
  $$MouseEvent ,
  $$MutationObserver ,
  $$MutationRecord ,
  $$NamedNodeMap ,
  $$Node ,
  $$NodeFilter ,
  $$NodeIterator ,
  $$NodeList ,
  $$PageTransitionEvent ,
  $$PointerEvent ,
  $$PopStateEvent ,
  $$ProcessingInstruction ,
  $$ProgressEvent ,
  $$RadioNodeList ,
  $$Range ,
  RectList ,
  RelatedEvent ,
  $$Selection ,
  $$ShadowRoot ,
  $$StaticRange ,
  $$StorageEvent ,
  SvgZoomEvent ,
  $$Text ,
  TimeEvent ,
  $$TouchEvent ,
  $$TrackEvent ,
  $$TransitionEvent ,
  $$TreeWalker ,
  UiEvent ,
  $$ValidityState ,
  WebGlContextEvent ,
  $$WheelEvent ,
  $$Window ,
  encodeCompareHow ,
  decodeCompareResult ,
  decodeCompatMode ,
  encodeContentEditable ,
  decodeContentEditable ,
  decodeDeltaMode ,
  encodeDesignMode ,
  decodeDesignMode ,
  encodeDir ,
  decodeDir ,
  EventPhase ,
  encodeFilterAction ,
  encodeInsertPosition ,
  encodeModifierKey ,
  decodeNodeType ,
  decodePointerType ,
  decodeReadyState ,
  decodeShadowRootMode ,
  decodeVisibilityState ,
  WhatToShow ,
  MxElement ,
  $$MediaQueryList ,
  
}
/* Webapi__Dom__Element Not a pure module */
