// Generated by ReScript, PLEASE EDIT WITH CARE


var isString = (function(c) { return typeof c === 'string' });

var isNumber = (function(c) { return typeof c === 'number' });

var Children = {
  isString: isString,
  isNumber: isNumber
};

export {
  Children ,
  
}
/* No side effect */
