// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MxLibs__DOM__MixinEvents from "./MxLibs__DOM__MixinEvents.js";

MxLibs__DOM__MixinEvents.Mixin({});

export {
  
}
/*  Not a pure module */
