// Generated by ReScript, PLEASE EDIT WITH CARE


var $$ResizeObserver;

var DomRect;

var $$Element;

var $$Window;

var $$Document;

var $$EventTarget;

export {
  $$ResizeObserver ,
  DomRect ,
  $$Element ,
  $$Window ,
  $$Document ,
  $$EventTarget ,
  
}
/* No side effect */
