// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MxLibs__DOM__EventTarget from "./MxLibs__DOM__EventTarget.js";

MxLibs__DOM__EventTarget.Mixin({});

export {
  
}
/*  Not a pure module */
