// Generated by ReScript, PLEASE EDIT WITH CARE


var $$ResizeObserver;

var DomRect;

var $$Element;

var $$Window;

export {
  $$ResizeObserver ,
  DomRect ,
  $$Element ,
  $$Window ,
  
}
/* No side effect */
