// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MxLibs__DOM_Node from "./MxLibs__DOM_Node.js";
import * as MxLibs__DOM__EventTarget from "./MxLibs__DOM__EventTarget.js";

MxLibs__DOM__EventTarget.Mixin({});

MxLibs__DOM_Node.Mixin({});

export {
  
}
/*  Not a pure module */
