// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_MutableMapInt from "rescript/lib/es6/belt_MutableMapInt.js";

var index = {
  contents: 0
};

var cache = Belt_MutableMapInt.fromArray([]);

function make(timesOpt, callback) {
  var times = timesOpt !== undefined ? timesOpt : 1;
  index.contents = index.contents + 1 | 0;
  var id = index.contents;
  var run = function (remaining) {
    if (remaining === 0) {
      Belt_MutableMapInt.remove(cache, id);
      return Curry._1(callback, undefined);
    }
    var rafid = requestAnimationFrame(function (param) {
          return run(remaining - 1 | 0);
        });
    return Belt_MutableMapInt.set(cache, id, rafid);
  };
  run(times);
  return id;
}

function cancel(id) {
  var rafid = Belt_MutableMapInt.get(cache, id);
  if (rafid !== undefined) {
    cancelAnimationFrame(rafid);
    Belt_MutableMapInt.remove(cache, id);
    return ;
  }
  
}

function throttle(timesOpt, callback) {
  var times = timesOpt !== undefined ? timesOpt : 1;
  var valid = {
    contents: true
  };
  return function (param) {
    if (valid.contents) {
      valid.contents = false;
      make(times, (function (param$1) {
              Curry._1(callback, param);
              valid.contents = true;
              
            }));
      return ;
    }
    
  };
}

function debounce(timesOpt, callback) {
  var times = timesOpt !== undefined ? timesOpt : 1;
  var id = {
    contents: undefined
  };
  return function (a1) {
    var id$1 = id.contents;
    if (id$1 !== undefined) {
      cancel(id$1);
    }
    id.contents = make(times, (function (param) {
            return Curry._1(callback, a1);
          }));
    
  };
}

export {
  make ,
  cancel ,
  throttle ,
  debounce ,
  
}
/* cache Not a pure module */
