// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import ResizeObserverPolyfill from "resize-observer-polyfill";

var $$ResizeObserverEntry = {};

var $$ResizeObserver = {};

var mapTargetCallbacks = new Map();

var observer = new ResizeObserverPolyfill((function (entries) {
        entries.forEach(function (entry) {
              var callbacks = mapTargetCallbacks.get(entry.target);
              if (callbacks !== undefined) {
                Caml_option.valFromOption(callbacks).forEach(function (callback) {
                      return Curry._1(callback, entry);
                    });
                return ;
              }
              
            });
        
      }));

function observe(element, callback) {
  var callbacks = mapTargetCallbacks.get(element);
  if (callbacks !== undefined) {
    Caml_option.valFromOption(callbacks).add(callback);
    return ;
  }
  observer.observe(element);
  var callbacks$1 = new Set().add(callback);
  mapTargetCallbacks.set(element, callbacks$1);
  
}

function unobserve(element, callback) {
  var callbacks = mapTargetCallbacks.get(element);
  if (callbacks === undefined) {
    return ;
  }
  var callbacks$1 = Caml_option.valFromOption(callbacks);
  callbacks$1.delete(callback);
  if (callbacks$1.size === 0) {
    observer.unobserve(element);
    return ;
  }
  
}

export {
  $$ResizeObserverEntry ,
  $$ResizeObserver ,
  observe ,
  unobserve ,
  
}
/* mapTargetCallbacks Not a pure module */
