// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MxLibs__ResizeObserver from "./MxLibs__ResizeObserver.js";

var $$ResizeObserver = MxLibs__ResizeObserver;

export {
  $$ResizeObserver ,
  
}
/* MxLibs__ResizeObserver Not a pure module */
