// Generated by ReScript, PLEASE EDIT WITH CARE


var STD;

var Dom;

var $$ResizeObserver;

var Raf;

var SingleResizeObserver;

export {
  STD ,
  Dom ,
  $$ResizeObserver ,
  Raf ,
  SingleResizeObserver ,
  
}
/* No side effect */
