// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var collections = new Map();

var observer = new ResizeObserver((function (entries) {
        entries.forEach(function (entry) {
              var callbacks = collections.get(entry.target);
              if (callbacks !== undefined) {
                Caml_option.valFromOption(callbacks).forEach(function (callback) {
                      return Curry._1(callback, entry);
                    });
                return ;
              }
              
            });
        
      }));

function observe(element, callback) {
  var callbacks = collections.get(element);
  if (callbacks !== undefined) {
    Caml_option.valFromOption(callbacks).add(callback);
    return ;
  }
  observer.observe(element);
  var callbacks$1 = new Set().add(callback);
  collections.set(element, callbacks$1);
  
}

function unobserve(element, callback) {
  var callbacks = collections.get(element);
  if (callbacks === undefined) {
    return ;
  }
  var callbacks$1 = Caml_option.valFromOption(callbacks);
  callbacks$1.delete(callback);
  if (callbacks$1.size === 0) {
    observer.unobserve(element);
    return ;
  }
  
}

var $$ResizeObserverEntry;

export {
  $$ResizeObserverEntry ,
  observe ,
  unobserve ,
  
}
/* collections Not a pure module */
