// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_MutableMapInt from "rescript/lib/es6/belt_MutableMapInt.js";

var index = {
  contents: 0
};

var store = Belt_MutableMapInt.fromArray([]);

function make(timesOpt, callback) {
  var times = timesOpt !== undefined ? timesOpt : 1;
  index.contents = index.contents + 1 | 0;
  var id = index.contents;
  var run = function (remaining) {
    if (remaining === 0) {
      return Curry._1(callback, Belt_MutableMapInt.clear(store));
    }
    var rafid = requestAnimationFrame(function (param) {
          return run(remaining - 1 | 0);
        });
    return Belt_MutableMapInt.set(store, id, rafid);
  };
  run(times);
  return id;
}

function cancel(id) {
  return Belt_Option.forEach(Belt_MutableMapInt.get(store, id), (function (rafid) {
                cancelAnimationFrame(rafid);
                Belt_MutableMapInt.remove(store, id);
                
              }));
}

function throttle(timesOpt, callback) {
  var times = timesOpt !== undefined ? timesOpt : 1;
  var valid = {
    contents: true
  };
  return function (param) {
    if (valid.contents) {
      valid.contents = false;
      make(times, (function (param$1) {
              Curry._1(callback, param);
              valid.contents = true;
              
            }));
      return ;
    }
    
  };
}

function debounce(timesOpt, callback) {
  var times = timesOpt !== undefined ? timesOpt : 1;
  var id = {
    contents: undefined
  };
  return function (a1) {
    var id$1 = id.contents;
    if (id$1 !== undefined) {
      cancel(id$1);
    }
    id.contents = make(times, (function (param) {
            return Curry._1(callback, a1);
          }));
    
  };
}

export {
  make ,
  cancel ,
  throttle ,
  debounce ,
  
}
/* store Not a pure module */
